### ISSUE TITLE
Create task list ui

### ISSUE THREAD

**Issue by ViincentLim** [ViincentLim/Tasky#1]
- [x] Lazy list with tasks
- [x] Create task ui
- [x] Delete task ui

**Comment by ViincentLim** [comment]
Completed as of the commit f876791
