### ISSUE TITLE
Link task list to database

### ISSUE THREAD

**Issue by ViincentLim** [ViincentLim/Tasky#2]
- [x] Model task data
- [x] Connect to database on both Android and iOS
- [x] Create task DAO
- [x] Link tasks to compose UI

**Comment by ViincentLim** [comment]
Completed as of the commit f876791
